services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    entrypoint: ./entrypoint.sh
    environment:
      MONGO_DB: mongodb://mongo:27017/
    networks:
      - voluntrack-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - voluntrack-net

networks:
  voluntrack-net:
    driver: bridge