version: '3'

services:
  web:
    image: helping-mamas-web
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    # env_file:
    #   - .env
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: mongo
    ports:
      - "27017:27017" # Expose MongoDB to host
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
